import { ShortCircuitParams, VoltageDropCalculation, IlluminationParams, LightFixture } from './types';

// PEC Table 3.10.1.16 (Copper THHN/THWN at 75°C)
export const WIRE_AMPACITY_TABLE = [
  { size: 2.0, ampacity: 20 },
  { size: 3.5, ampacity: 25 },
  { size: 5.5, ampacity: 35 },
  { size: 8.0, ampacity: 50 },
  { size: 14, ampacity: 65 },
  { size: 22, ampacity: 90 },
  { size: 30, ampacity: 110 },
  { size: 38, ampacity: 125 },
  { size: 50, ampacity: 150 },
  { size: 60, ampacity: 175 },
  { size: 80, ampacity: 200 },
  { size: 100, ampacity: 230 },
  { size: 125, ampacity: 255 },
  { size: 150, ampacity: 285 },
  { size: 175, ampacity: 310 },
  { size: 200, ampacity: 335 },
  { size: 250, ampacity: 380 },
  { size: 325, ampacity: 445 },
  { size: 400, ampacity: 490 },
  { size: 500, ampacity: 545 },
];

export const STANDARD_CB_RATINGS = [15, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 125, 150, 160, 175, 200, 225, 250, 300, 350, 400, 450, 500, 600, 700, 800, 900, 1000, 1200, 1600, 2000, 2500, 3200, 4000, 5000];

export const SYSTEM_VOLTAGES = {
  // Single-Phase Systems
  '230V, 1PH, 2W': 230,
  '230V, 1PH, 3W': 230,

  // Three-Phase, 5-Wire (3PH, 5W) Systems
  '115V/66V, 3PH, 5W': 115,
  '200V/115V, 3PH, 5W': 200,
  '208V/120V, 3PH, 5W': 208,
  '380V/220V, 3PH, 5W': 380,
  '380V/230V, 3PH, 5W': 380,
  '400V/230V, 3PH, 5W': 400,
  '415V/240V, 3PH, 5W': 415,
  '440V/230V, 3PH, 5W': 440,
  '460V/265V, 3PH, 5W': 460,
  '480V/230V, 3PH, 5W': 480,
  '480V/277V, 3PH, 5W': 480,
  '575V/330V, 3PH, 5W': 575,
  '600V/347V, 3PH, 5W': 600,
  '115V, 3PH, 5W': 115,
  '200V, 3PH, 5W': 200,
  '208V, 3PH, 5W': 208,
  '230V, 3PH, 5W': 230,
  '380V, 3PH, 5W': 380,
  '400V, 3PH, 5W': 400,
  '440V, 3PH, 5W': 440,
  '460V, 3PH, 5W': 460,
  '480V, 3PH, 5W': 480,
  '575V, 3PH, 5W': 575,

  // Three-Phase, 4-Wire (3PH, 4W) Systems
  '115V/66V, 3PH, 4W': 115,
  '200V/115V, 3PH, 4W': 200,
  '208V/120V, 3PH, 4W': 208,
  '380V/220V, 3PH, 4W': 380,
  '380V/230V, 3PH, 4W': 380,
  '400V/230V, 3PH, 4W': 400,
  '415V/240V, 3PH, 4W': 415,
  '440V/230V, 3PH, 4W': 440,
  '460V/265V, 3PH, 4W': 460,
  '480V/230V, 3PH, 4W': 480,
  '480V/277V, 3PH, 4W': 480,
  '575V/330V, 3PH, 4W': 575,
  '600V/347V, 3PH, 4W': 600,

  // Three-Phase, 3-Wire (3PH, 3W) Systems
  '115V, 3PH, 3W': 115,
  '200V, 3PH, 3W': 200,
  '208V, 3PH, 3W': 208,
  '230V, 3PH, 3W': 230,
  '380V, 3PH, 3W': 380,
  '400V, 3PH, 3W': 400,
  '440V, 3PH, 3W': 440,
  '460V, 3PH, 3W': 460,
  '480V, 3PH, 3W': 480,
  '575V, 3PH, 3W': 575,
};

export const INITIAL_SHORT_CIRCUIT_PARAMS: ShortCircuitParams = {
  transformerKVA: 100,
  transformerZ: 5,
  transformerVoltage: 230,
  primaryVoltage: 34500,
  transformerConnection: 'Delta-Wye (Δ-Y)',
  utilityShortCircuitMVA: 500,
  feederLength: 10,
  feederSize: '30',
  feederRuns: 1,
  conductorType: 'Copper',
  connectionType: 'Series',
  parallelTransformersCount: 1,
  parallelTransformersZMatch: true,
  parallelTransformerskVAMatch: true,
  parallelTransformersVoltageMatch: true,
  parallelTransformersPhaseMatch: true,
  parallelTransformersFreqMatch: true,
  parallelTransformersVectorMatch: true,
  parallelTransformersRating: 100,
  parallelTransformersZ: 5,
  parallelFeedersCount: 1,
  parallelFeedersSizeMatch: true,
  parallelFeedersLengthMatch: true,
  parallelFeedersMaterialMatch: true,
  parallelFeedersInsulationMatch: true,
  parallelFeedersCustomSizes: ['30', '30'],
  parallelFeedersCustomLengths: [10, 10],
  parallelFeedersCustomMaterials: ['Copper', 'Copper'],
  parallelFeedersCustomInsulations: ['THHN', 'THHN']
};

export const INITIAL_VOLTAGE_DROP_CALCULATIONS: VoltageDropCalculation[] = [
  {
    id: 'initial',
    source: 'custom',
    name: 'Custom Circuit',
    loadA: 20,
    length: 30,
    wireSize: '3.5',
    voltage: 230,
    systemType: '1PH'
  }
];
export const LIGHT_FIXTURES_LIBRARY: LightFixture[] = [
  // 1. Recessed LED Downlights
  {
    id: 'rec-downlight-9w',
    category: 'Recessed Downlights',
    lightType: 'Recessed LED Downlight (9W)',
    wattageRange: '5W–12W',
    lumensRange: '750–1000 lm',
    brands: 'Philips, Firefly, Omni, Akari',
    wattage: 9,
    lumens: 810,
    efficacy: 90,
    cct: '4000K (Neutral White)',
    cri: 85,
    mountingType: 'Recessed',
    beamAngle: 110,
    utilizationFactor: 0.65,
    manufacturerReference: 'PH-DL-9W-REC',
    description: 'High efficiency recessed LED downlight with frosted cover for glare-free lighting.'
  },
  {
    id: 'rec-downlight-15w',
    category: 'Recessed Downlights',
    lightType: 'Recessed LED Downlight (15W)',
    wattageRange: '12W–24W',
    lumensRange: '1200–2400 lm',
    brands: 'Philips, Firefly, Omni',
    wattage: 15,
    lumens: 1350,
    efficacy: 90,
    cct: '6500K (Daylight)',
    cri: 82,
    mountingType: 'Recessed',
    beamAngle: 110,
    utilizationFactor: 0.65,
    manufacturerReference: 'PH-DL-15W-REC',
    description: 'A bright recessed light designed for commercial and office ceilings.'
  },

  // 2. Surface-Mounted LED Lights
  {
    id: 'surf-mounted-18w',
    category: 'Surface Mounted',
    lightType: 'Surface-Mounted LED Ceiling Light',
    wattageRange: '12W–30W',
    lumensRange: '1000–3000 lm',
    brands: 'Omni, Akari, Firefly',
    wattage: 18,
    lumens: 1620,
    efficacy: 90,
    cct: '3000K (Warm White)',
    cri: 82,
    mountingType: 'Surface-mounted',
    beamAngle: 120,
    utilizationFactor: 0.60,
    manufacturerReference: 'OM-SM-18W-RND',
    description: 'Minimalist circular surface-mounted ceiling fixture.'
  },

  // 3. LED Panel Lights (300x300, 600x600, 1200x600)
  {
    id: 'panel-300',
    category: 'Panel Lights',
    lightType: 'LED Panel (300x300)',
    wattageRange: '10W–18W',
    lumensRange: '900–1600 lm',
    brands: 'Philips, Akari, Firefly',
    wattage: 12,
    lumens: 1085,
    efficacy: 90,
    cct: '4000K (Neutral White)',
    cri: 80,
    mountingType: 'Recessed / Suspended',
    beamAngle: 120,
    utilizationFactor: 0.68,
    manufacturerReference: 'AK-PL-3030-12W',
    description: 'Compact square panel light suitable for narrow corridors and washrooms.'
  },
  {
    id: 'panel-600',
    category: 'Panel Lights',
    lightType: 'LED Panel (600x600)',
    wattageRange: '24W–48W',
    lumensRange: '2400–5000 lm',
    brands: 'Philips, Firefly, Omni',
    wattage: 36,
    lumens: 3600,
    efficacy: 100,
    cct: '6500K (Daylight)',
    cri: 85,
    mountingType: 'Recessed',
    beamAngle: 120,
    utilizationFactor: 0.75,
    manufacturerReference: 'PH-RC-PL6060-36W',
    description: 'Standard office layout professional grid recessed LED panel.'
  },
  {
    id: 'panel-1200',
    category: 'Panel Lights',
    lightType: 'LED Panel (1200x600)',
    wattageRange: '60W–90W',
    lumensRange: '6000–9500 lm',
    brands: 'Philips, Omni',
    wattage: 72,
    lumens: 7200,
    efficacy: 100,
    cct: '5000K (Cool White)',
    cri: 90,
    mountingType: 'Recessed / Suspended',
    beamAngle: 120,
    utilizationFactor: 0.78,
    manufacturerReference: 'PH-PL1260-72W',
    description: 'Large format ultra-slim high output rectangular panel light.'
  },

  // 4. Linear LED Fixtures
  {
    id: 'linear-fixture-4ft',
    category: 'Linear & Batten',
    lightType: 'Linear LED Pendant Fixture (4ft)',
    wattageRange: '30W–50W',
    lumensRange: '3000–5500 lm',
    brands: 'Philips, Akari, Custom',
    wattage: 40,
    lumens: 4400,
    efficacy: 110,
    cct: '4000K (Neutral White)',
    cri: 85,
    mountingType: 'Suspended / Pendant',
    beamAngle: 105,
    utilizationFactor: 0.70,
    manufacturerReference: 'PH-LN-4FT-S',
    description: 'Suspended modern architectural linear luminaire with continuous mounting capability.'
  },

  // 5. Troffer Lights
  {
    id: 'troffer-2x4',
    category: 'Panel Lights',
    lightType: 'Standard Recessed Troffer (2x4)',
    wattageRange: '30W–60W',
    lumensRange: '3500–6600 lm',
    brands: 'Omni, Philips, GE',
    wattage: 45,
    lumens: 4950,
    efficacy: 110,
    cct: '4000K (Neutral White)',
    cri: 82,
    mountingType: 'Recessed',
    beamAngle: 115,
    utilizationFactor: 0.72,
    manufacturerReference: 'OM-TRF-24-45W',
    description: 'Parabolic architectural troffer for dust protection and soft spread.'
  },

  // 6. LED Batten Lights
  {
    id: 'batten-light-20w',
    category: 'Linear & Batten',
    lightType: 'Integrated LED Batten Light',
    wattageRange: '10W–30W',
    lumensRange: '1000–3300 lm',
    brands: 'Philips, Firefly, Omni',
    wattage: 20,
    lumens: 2000,
    efficacy: 100,
    cct: '6500K (Daylight)',
    cri: 80,
    mountingType: 'Surface-mounted',
    beamAngle: 120,
    utilizationFactor: 0.68,
    manufacturerReference: 'FF-BT-4FT-20W',
    description: 'Slim integrated alternative to traditional fluorescent tube battens.'
  },

  // 7. Industrial High-Bay Fixtures
  {
    id: 'high-bay-150w',
    category: 'Industrial & High-Bay',
    lightType: 'Industrial UFO LED High-Bay',
    wattageRange: '100W–240W',
    lumensRange: '15000–36000 lm',
    brands: 'Omni, Firefly, Philips, GE',
    wattage: 150,
    lumens: 22500,
    efficacy: 150,
    cct: '5000K (Cool White)',
    cri: 80,
    mountingType: 'Suspended / Hook',
    beamAngle: 90,
    utilizationFactor: 0.82,
    manufacturerReference: 'OM-UFO-150W-IP65',
    description: 'Heavy duty IP65 high bay light for warehouses, gyms and factories.'
  },

  // 8. Low-Bay Fixtures
  {
    id: 'low-bay-80w',
    category: 'Industrial & High-Bay',
    lightType: 'Industrial LED Low-Bay Fixture',
    wattageRange: '50W–100W',
    lumensRange: '6000–12000 lm',
    brands: 'Philips, Omni, Akari',
    wattage: 80,
    lumens: 9600,
    efficacy: 120,
    cct: '4000K (Neutral White)',
    cri: 80,
    mountingType: 'Surface / Suspended',
    beamAngle: 120,
    utilizationFactor: 0.75,
    manufacturerReference: 'AK-LB-80W-IND',
    description: 'Widespread commercial-grade low ceiling industrial lighting.'
  },

  // 9. Floodlights
  {
    id: 'flood-led-100w',
    category: 'Outdoor & Street',
    lightType: 'Outdoor LED Floodlight',
    wattageRange: '50W–300W',
    lumensRange: '5500–33000 lm',
    brands: 'Akari, Firefly, Omni',
    wattage: 100,
    lumens: 11000,
    efficacy: 110,
    cct: '6500K (Daylight)',
    cri: 75,
    mountingType: 'Surface (Yoke)',
    beamAngle: 110,
    utilizationFactor: 0.60,
    manufacturerReference: 'FF-FL-100W-IP66',
    description: 'Waterproof IP66 architectural floodlight for external perimeters.'
  },

  // 10. Street Lights
  {
    id: 'street-light-120w',
    category: 'Outdoor & Street',
    lightType: 'LED Street Light',
    wattageRange: '50W–200W',
    lumensRange: '6000–24000 lm',
    brands: 'Omni, Philips, GE',
    wattage: 120,
    lumens: 14400,
    efficacy: 120,
    cct: '5700K (Daylight)',
    cri: 70,
    mountingType: 'Pole mounted',
    beamAngle: 140,
    utilizationFactor: 0.55,
    manufacturerReference: 'OM-SL-120W-ST',
    description: 'Type II optic street light optimized for pathways, driveways and main roads.'
  },

  // 11. Area Lights
  {
    id: 'area-shoebox-200w',
    category: 'Outdoor & Street',
    lightType: 'LED Area Shoebox Parking Light',
    wattageRange: '100W–300W',
    lumensRange: '13000–39000 lm',
    brands: 'Philips, Omni',
    wattage: 200,
    lumens: 26000,
    efficacy: 130,
    cct: '5000K (Cool White)',
    cri: 75,
    mountingType: 'Pole slipfitter',
    beamAngle: 130,
    utilizationFactor: 0.58,
    manufacturerReference: 'PH-SB-200W-V4',
    description: 'High capacity parking lot shoebox light with pole-mount attachment.'
  },

  // 12. Wall-Mounted Lights
  {
    id: 'wall-pack-30w',
    category: 'Outdoor & Street',
    lightType: 'LED Wall Pack Light',
    wattageRange: '15W–50W',
    lumensRange: '1600–5500 lm',
    brands: 'Firefly, Akari, Philips',
    wattage: 30,
    lumens: 3300,
    efficacy: 110,
    cct: '4000K (Neutral White)',
    cri: 80,
    mountingType: 'Wall-mounted',
    beamAngle: 100,
    utilizationFactor: 0.50,
    manufacturerReference: 'FF-WP-30W-LED',
    description: 'Durable external perimeter wall lamp with integrated photo-cell compatibility.'
  },

  // 13. Bollard Lights
  {
    id: 'bollard-light-15w',
    category: 'Landscape & Specialty',
    lightType: 'LED Pathway Bollard Light',
    wattageRange: '8W–25W',
    lumensRange: '600–2000 lm',
    brands: 'Philips, Omni, Landscaping',
    wattage: 15,
    lumens: 1200,
    efficacy: 80,
    cct: '3000K (Warm White)',
    cri: 82,
    mountingType: 'Ground / Flange mounted',
    beamAngle: 360,
    utilizationFactor: 0.35,
    manufacturerReference: 'PH-BLD-15W-3K',
    description: 'Elegant cylindrical architectural ground bollard for pathways and lawns.'
  },

  // 14. Emergency Lights
  {
    id: 'emergency-twin-head',
    category: 'Emergency & Exit',
    lightType: 'Twin-Head LED Emergency Backup Light',
    wattageRange: '3W–15W',
    lumensRange: '300–1200 lm',
    brands: 'Firefly, Omni, Akari',
    wattage: 12,
    lumens: 1100,
    efficacy: 91.6,
    cct: '6500K (Daylight)',
    cri: 75,
    mountingType: 'Wall-mounted',
    beamAngle: 90,
    utilizationFactor: 0.50,
    manufacturerReference: 'FF-EMG-TW-12',
    description: 'Automatic backup battery twin head spotlight for building exit routing.'
  },

  // 15. Exit Sign Lights
  {
    id: 'exit-sign-led',
    category: 'Emergency & Exit',
    lightType: 'LED Emergency Exit Sign (Green/Red)',
    wattageRange: '2W–6W',
    lumensRange: '100–300 lm',
    brands: 'Firefly, Akari, Omni',
    wattage: 4,
    lumens: 255,
    efficacy: 63.7,
    cct: 'Green LED Spectrum',
    cri: 70,
    mountingType: 'Wall / Ceiling',
    beamAngle: 180,
    utilizationFactor: 0.40,
    manufacturerReference: 'OM-EXT-SG-GRN',
    description: 'Double-sided green acrylic panel exit sign with internal battery backup.'
  },

  // 16. Pendant Lights
  {
    id: 'pendant-modern-25w',
    category: 'Aesthetic & Decorative',
    lightType: 'Modern LED Pendant Fixture',
    wattageRange: '10W–40W',
    lumensRange: '800–3500 lm',
    brands: 'Philips, Custom Decorative',
    wattage: 25,
    lumens: 2000,
    efficacy: 80,
    cct: '3000K (Warm White)',
    cri: 90,
    mountingType: 'Suspended (Pendant)',
    beamAngle: 90,
    utilizationFactor: 0.58,
    manufacturerReference: 'PH-MDRN-PD-25',
    description: 'Stylish minimalist dome pendant lamp for residential rooms or lobbies.'
  },

  // 17. Chandeliers
  {
    id: 'chandelier-led-60w',
    category: 'Aesthetic & Decorative',
    lightType: 'Elegance Crystal Chandelier LED',
    wattageRange: '40W–150W',
    lumensRange: '3000–12000 lm',
    brands: 'Custom Decorative, Philips',
    wattage: 60,
    lumens: 4800,
    efficacy: 80,
    cct: '2700K (Soft Warm)',
    cri: 92,
    mountingType: 'Suspended (Chain)',
    beamAngle: 360,
    utilizationFactor: 0.45,
    manufacturerReference: 'CH-XSTAL-60W',
    description: 'High luxury decorative chandelier combining candle warm light arrays.'
  },

  // 18. Track Lights
  {
    id: 'track-light-15w',
    category: 'Track & Spotlights',
    lightType: 'Adjustable LED Track Light',
    wattageRange: '7W–30W',
    lumensRange: '600–2800 lm',
    brands: 'Philips, Omni, Akari',
    wattage: 15,
    lumens: 1350,
    efficacy: 90,
    cct: '3000K (Warm White)',
    cri: 90,
    mountingType: 'Track mounted',
    beamAngle: 36,
    utilizationFactor: 0.60,
    manufacturerReference: 'PH-TRK-15W-AD',
    description: 'Rotatable spotlight with narrow beam for highlighting product catalog displays.'
  },

  // 19. Spotlights
  {
    id: 'spotlight-led-7w',
    category: 'Track & Spotlights',
    lightType: 'Directional LED Spotlight (GU10)',
    wattageRange: '3W–12W',
    lumensRange: '250–1000 lm',
    brands: 'Philips, Firefly',
    wattage: 7,
    lumens: 560,
    efficacy: 80,
    cct: '3000K (Warm White)',
    cri: 88,
    mountingType: 'Recessed / Track',
    beamAngle: 24,
    utilizationFactor: 0.55,
    manufacturerReference: 'FF-SP-7W-GU10',
    description: 'Pin-point spotlight lens suitable for retail accents and museum galleries.'
  },

  // 20. Under-Cabinet Lights
  {
    id: 'undercab-led-10w',
    category: 'Landscape & Specialty',
    lightType: 'Slim LED Under-Cabinet Bar',
    wattageRange: '5W–15W',
    lumensRange: '400–1300 lm',
    brands: 'Omni, Philips, Firefly',
    wattage: 10,
    lumens: 900,
    efficacy: 90,
    cct: '3500K (Warm Neutral)',
    cri: 85,
    mountingType: 'Surface (Adhesive/Screws)',
    beamAngle: 110,
    utilizationFactor: 0.58,
    manufacturerReference: 'OM-UCB-10W-3CCT',
    description: 'Low-profile rigid LED light extrusion for kitchens and laboratory workbenches.'
  },

  // 21. Garden and Landscape Lights
  {
    id: 'garden-spike-5w',
    category: 'Landscape & Specialty',
    lightType: 'LED Garden Spike Spotlight',
    wattageRange: '3W–10W',
    lumensRange: '200–800 lm',
    brands: 'Philips, Akari, Landscaping',
    wattage: 5,
    lumens: 400,
    efficacy: 80,
    cct: '3000K (Warm White)',
    cri: 82,
    mountingType: 'Ground Spike (Soil)',
    beamAngle: 45,
    utilizationFactor: 0.40,
    manufacturerReference: 'AK-GSP-5W-IP67',
    description: 'Sturdy ground insertion lighting for bushes, trees and exterior paths.'
  },

  // 22. Canopy Lights
  {
    id: 'canopy-fuel-120w',
    category: 'Industrial & High-Bay',
    lightType: 'Soffit Canopy Gas Station LED',
    wattageRange: '80W–150W',
    lumensRange: '10000–20000 lm',
    brands: 'Philips, GE, Omni',
    wattage: 120,
    lumens: 15600,
    efficacy: 130,
    cct: '5000K (Cool White)',
    cri: 80,
    mountingType: 'Recessed / Surface',
    beamAngle: 110,
    utilizationFactor: 0.80,
    manufacturerReference: 'PH-CNP-120W',
    description: 'High durability soffit recessed fixture for petrol station canopies and loading docks.'
  },

  // 23. Waterproof/IP-Rated Fixtures
  {
    id: 'tri-proof-ip65-40w',
    category: 'Landscape & Specialty',
    lightType: 'Tri-Proof IP65 Waterproof LED Fixture',
    wattageRange: '20W–60W',
    lumensRange: '2200–7200 lm',
    brands: 'Philips, Firefly, Omni',
    wattage: 40,
    lumens: 4800,
    efficacy: 120,
    cct: '6500K (Daylight)',
    cri: 80,
    mountingType: 'Surface / Suspended',
    beamAngle: 120,
    utilizationFactor: 0.70,
    manufacturerReference: 'FF-TP-40W-IP65',
    description: 'Vapor-tight waterproof, dustproof and corrosion-proof linear light for tunnels and parking bays.'
  },
  
  // 24. Deep Anti-Glare Comfort Downlights
  {
    id: 'deep-comfort-dl-12w',
    category: 'Recessed Downlights',
    lightType: 'Deep-Baffle Anti-Glare Comfort Downlight (12W)',
    wattageRange: '8W–15W',
    lumensRange: '700–1400 lm',
    brands: 'Cree, Philips, Custom Spec',
    wattage: 12,
    lumens: 1020,
    efficacy: 85,
    cct: '3000K (Warm White)',
    cri: 93,
    mountingType: 'Recessed',
    beamAngle: 60,
    utilizationFactor: 0.62,
    manufacturerReference: 'CR-DB-12W-930',
    description: 'Premium architectural downlight with UGR<19 deep-recessed micro-baffle for maximum visual comfort.'
  },

  // 25. Adjustable Gimbal Accents
  {
    id: 'gimbal-accent-8w',
    category: 'Track & Spotlights',
    lightType: 'Adjustable Recessed Gimbal Downlight (8W)',
    wattageRange: '5W–12W',
    lumensRange: '450–1100 lm',
    brands: 'Omni, Akari, Philips',
    wattage: 8,
    lumens: 680,
    efficacy: 85,
    cct: '2700K (Warm White)',
    cri: 90,
    mountingType: 'Recessed',
    beamAngle: 30,
    utilizationFactor: 0.55,
    manufacturerReference: 'OM-GMB-8W-30D',
    description: '30-degree rotatable recessed gimbal tilt fixture for highlighting artwork or features.'
  },

  // 26. Slim Square Ceiling Surfaces
  {
    id: 'slim-square-surface-24w',
    category: 'Surface Mounted',
    lightType: 'Slim Square Surface-Mounted Panel (24W)',
    wattageRange: '18W–36W',
    lumensRange: '1600–3200 lm',
    brands: 'Firefly, Omni',
    wattage: 24,
    lumens: 2160,
    efficacy: 90,
    cct: '4000K (Neutral White)',
    cri: 80,
    mountingType: 'Surface-mounted',
    beamAngle: 120,
    utilizationFactor: 0.62,
    manufacturerReference: 'FF-SQ-SM-24W',
    description: 'Compact ultra-thin square surface luminaire for utility areas, closets, and kitchens.'
  },

  // 27. Modern Minimalist Multi-Ring Pendant
  {
    id: 'halo-multi-ring-50w',
    category: 'Aesthetic & Decorative',
    lightType: 'Nordic Circular Halo LED Pendant (50W)',
    wattageRange: '30W–80W',
    lumensRange: '2500–7000 lm',
    brands: 'Custom Spec, Philips',
    wattage: 50,
    lumens: 4250,
    efficacy: 85,
    cct: '3000K (Warm White)',
    cri: 90,
    mountingType: 'Suspended (Pendant)',
    beamAngle: 180,
    utilizationFactor: 0.50,
    manufacturerReference: 'ND-HL-50W-3K',
    description: 'Stunning tiered triple circular halo designer light offering 360-degree ambient distribution.'
  },

  // 28. High Temperature Protected Linear Low-Bay
  {
    id: 'linear-low-bay-60w',
    category: 'Industrial & High-Bay',
    lightType: 'Linear High-Efficacy Low-Bay Fixture (60W)',
    wattageRange: '40W–80W',
    lumensRange: '5000–11000 lm',
    brands: 'GE, Omni, Philips',
    wattage: 60,
    lumens: 7800,
    efficacy: 130,
    cct: '5000K (Cool White)',
    cri: 82,
    mountingType: 'Surface / Suspended',
    beamAngle: 110,
    utilizationFactor: 0.78,
    manufacturerReference: 'GE-LLB-60W-V2',
    description: 'Rugged dust-sealed impact-resistant low-bay linear luminaire ideal for assembly lines and workshops.'
  },

  // 29. Sol-Integrated Smart Streetlight
  {
    id: 'solar-all-in-one-60w',
    category: 'Outdoor & Street',
    lightType: 'Solar Fully Integrated All-in-One Streetlight (60W)',
    wattageRange: '30W–100W',
    lumensRange: '4500–15000 lm',
    brands: 'Custom-Green, Akari',
    wattage: 60,
    lumens: 9000,
    efficacy: 150,
    cct: '5700K (Daylight)',
    cri: 70,
    mountingType: 'Pole mounted',
    beamAngle: 150,
    utilizationFactor: 0.52,
    manufacturerReference: 'AK-SOL-60W',
    description: 'Zero-grid intelligent solar streetlight with high-capacity LiFePO4 battery and built-in motion sensor.'
  },

  // 30. Architectural Landscape Wall Grazer
  {
    id: 'wall-grazer-rgbw-36w',
    category: 'Landscape & Specialty',
    lightType: 'Linear Architectural Wall Grazer (36W)',
    wattageRange: '24W–48W',
    lumensRange: '2000–4500 lm',
    brands: 'Philips, Custom Spec',
    wattage: 36,
    lumens: 2880,
    efficacy: 80,
    cct: '3000K Warm + Interactive Config',
    cri: 85,
    mountingType: 'Surface (Yoke)',
    beamAngle: 15,
    utilizationFactor: 0.45,
    manufacturerReference: 'PH-WG-36W-IP67',
    description: 'Narrow-beam outdoor IP67 linear wall projector for sweeping illumination of building textures and facades.'
  },

  // --- NEW COMPREHENSIVE FIXTURE EXPANSIONS ---

  // 31. LED Panel Lights
  {
    id: 'panel-edge-40w',
    category: 'LED Panel Lights',
    lightType: 'Edge-Lit LED Panel Light (40W)',
    wattageRange: '30W–50W',
    lumensRange: '3500–5500 lm',
    brands: 'Philips, Ledvance, Lithonia',
    manufacturer: 'Philips',
    modelNumber: 'PL-EDGE-40W-6060',
    wattage: 40,
    lumens: 4400,
    efficacy: 110,
    cct: '4000K (Neutral White)',
    cri: 82,
    mountingType: 'Recessed / Suspended',
    beamAngle: 120,
    utilizationFactor: 0.72,
    manufacturerReference: 'PH-PL-EDGE-40W',
    ipRating: 'IP40',
    dimensions: '595x595x10 mm',
    typicalApplication: 'Commercial offices, conference rooms, educational facilities',
    lifespan: '50,000 hrs',
    dimmable: 'Yes (0-10V)',
    description: 'Ultra-thin architectural edge-lit panel delivering extremely uniform glare-free light distribution.'
  },

  // 32. LED Troffers
  {
    id: 'troffer-arch-36w',
    category: 'LED Troffers',
    lightType: 'Architectural Curved LED Troffer (36W)',
    wattageRange: '24W–48W',
    lumensRange: '3000–5000 lm',
    brands: 'Lithonia Lighting, Columbia, GE',
    manufacturer: 'Lithonia Lighting',
    modelNumber: '2VTL4-36W-ADP',
    wattage: 36,
    lumens: 4320,
    efficacy: 120,
    cct: '3500K (Warm White)',
    cri: 85,
    mountingType: 'Recessed Grid',
    beamAngle: 115,
    utilizationFactor: 0.74,
    manufacturerReference: 'LT-2VTL4-36W',
    ipRating: 'IP30',
    dimensions: '1198x598x80 mm',
    typicalApplication: 'Modern office areas, healthcare exam rooms, institutional corridors',
    lifespan: '60,000 hrs',
    dimmable: 'Yes (0-10V)',
    description: 'Volumetric troffer with curved center basket reflector for high efficiency soft general illumination.'
  },

  // 33. LED Downlights (Recessed & Surface Mounted)
  {
    id: 'downlight-rec-deep-12w',
    category: 'LED Downlights (Recessed & Surface)',
    lightType: 'Deep Recessed LED Downlight (12W)',
    wattageRange: '8W–18W',
    lumensRange: '700–1600 lm',
    brands: 'Cree Lighting, Philips, Omni',
    manufacturer: 'Cree Lighting',
    modelNumber: 'CR-DL-REC-12',
    wattage: 12,
    lumens: 1100,
    efficacy: 91.6,
    cct: '3000K (Warm White)',
    cri: 90,
    mountingType: 'Recessed',
    beamAngle: 60,
    utilizationFactor: 0.65,
    manufacturerReference: 'CR-DL-REC-12W',
    ipRating: 'IP44',
    dimensions: '110x110x85 mm',
    typicalApplication: 'Residential suites, upscale hotel guestrooms, visual-comfort office zones',
    lifespan: '50,000 hrs',
    dimmable: 'Yes (TRIAC)',
    description: 'Deep-recessed glare-blocking baffle downlight featuring premium high color rendering index LED engine.'
  },
  {
    id: 'downlight-surf-cyl-15w',
    category: 'LED Downlights (Recessed & Surface)',
    lightType: 'Surface Mounted Cylindrical Downlight (15W)',
    wattageRange: '10W–24W',
    lumensRange: '900–2200 lm',
    brands: 'Omni, Akari, Firefly',
    manufacturer: 'Omni',
    modelNumber: 'CYL-DL-SM-15',
    wattage: 15,
    lumens: 1400,
    efficacy: 93.3,
    cct: '4000K (Neutral White)',
    cri: 85,
    mountingType: 'Surface-mounted',
    beamAngle: 90,
    utilizationFactor: 0.62,
    manufacturerReference: 'OM-CYL-SM-15W',
    ipRating: 'IP40',
    dimensions: '120x120x150 mm',
    typicalApplication: 'Exposed high ceilings, commercial lobbies, retail storefronts, cafes',
    lifespan: '45,000 hrs',
    dimmable: 'No',
    description: 'Architectural cylinder luminaire designed for direct ceiling mounting where recessing is not feasible.'
  },

  // 34. COB Downlights
  {
    id: 'cob-downlight-retail-25w',
    category: 'COB Downlights',
    lightType: 'High-Output COB Accent Downlight (25W)',
    wattageRange: '15W–35W',
    lumensRange: '1500–3800 lm',
    brands: 'Philips, Ledvance, Custom Spec',
    manufacturer: 'Philips',
    modelNumber: 'PH-COB-ACC-25',
    wattage: 25,
    lumens: 2500,
    efficacy: 100,
    cct: '3000K (Warm White)',
    cri: 92,
    mountingType: 'Recessed',
    beamAngle: 45,
    utilizationFactor: 0.68,
    manufacturerReference: 'PH-COB-ACC-25W',
    ipRating: 'IP20',
    dimensions: '150x150x110 mm',
    typicalApplication: 'Luxury car showrooms, high-end retail boutique spotlights, hotel counters',
    lifespan: '50,000 hrs',
    dimmable: 'Yes (0-10V)',
    description: 'Chip-on-Board (COB) single-point light source fixture with reflector optics for intense focal beams.'
  },

  // 35. LED Spotlights
  {
    id: 'spotlight-pin-5w',
    category: 'LED Spotlights',
    lightType: 'Mini Pin-Hole LED Accent Spotlight (5W)',
    wattageRange: '3W–10W',
    lumensRange: '250–900 lm',
    brands: 'Akari, Firefly, Omni',
    manufacturer: 'Akari',
    modelNumber: 'AK-PIN-SPOT-5',
    wattage: 5,
    lumens: 450,
    efficacy: 90,
    cct: '2700K (Warm White)',
    cri: 90,
    mountingType: 'Recessed',
    beamAngle: 24,
    utilizationFactor: 0.58,
    manufacturerReference: 'AK-PIN-SPOT-5W',
    ipRating: 'IP20',
    dimensions: '65x65x50 mm',
    typicalApplication: 'Museum showcases, residential art displays, built-in display shelving',
    lifespan: '30,000 hrs',
    dimmable: 'Yes (TRIAC)',
    description: 'Miniature point spotlight with micro-bezel for subtle spotlighting with minimum hardware exposure.'
  },

  // 36. LED Track Lights
  {
    id: 'track-zoom-20w',
    category: 'LED Track Lights',
    lightType: 'Zoomable Focus LED Track Light (20W)',
    wattageRange: '15W–30W',
    lumensRange: '1300–2800 lm',
    brands: 'Omni, Philips, Ledvance',
    manufacturer: 'Omni',
    modelNumber: 'OM-TRK-ZM-20',
    wattage: 20,
    lumens: 1800,
    efficacy: 90,
    cct: '3000K (Warm White)',
    cri: 90,
    mountingType: 'Track mounted',
    beamAngle: 36,
    utilizationFactor: 0.60,
    manufacturerReference: 'OM-TRK-ZM-20W',
    ipRating: 'IP20',
    dimensions: '80x150x200 mm',
    typicalApplication: 'Art galleries, visual museums, retail clothing lines, creative office zones',
    lifespan: '40,000 hrs',
    dimmable: 'Yes (Phase Cut)',
    description: 'Rotatable track fixture with adjustable focal barrel to transition beam spot dynamically.'
  },

  // 37. LED Linear Lights
  {
    id: 'linear-arch-recessed-28w',
    category: 'LED Linear Lights',
    lightType: 'Recessed Architectural Seamless Linear (28W)',
    wattageRange: '20W–45W',
    lumensRange: '2200–5000 lm',
    brands: 'Ledvance, Columbia, Custom Spec',
    manufacturer: 'Ledvance',
    modelNumber: 'LD-LIN-REC-28',
    wattage: 28,
    lumens: 3080,
    efficacy: 110,
    cct: '4000K (Neutral White)',
    cri: 85,
    mountingType: 'Recessed (Seamless)',
    beamAngle: 105,
    utilizationFactor: 0.70,
    manufacturerReference: 'LD-LIN-REC-28W',
    ipRating: 'IP40',
    dimensions: '1200x50x75 mm',
    typicalApplication: 'Corporate offices, public libraries, minimalist modern hallways, boardrooms',
    lifespan: '50,000 hrs',
    dimmable: 'Yes (0-10V)',
    description: 'Recessed continuous extrusion profile linear luminaire for uninterrupted clean lines of light.'
  },

  // 38. LED Batten Lights
  {
    id: 'batten-linkable-18w',
    category: 'LED Batten Lights',
    lightType: 'Linkable Integrated LED Batten (18W)',
    wattageRange: '10W–28W',
    lumensRange: '1000–3100 lm',
    brands: 'Firefly, Omni, Philips',
    manufacturer: 'Firefly',
    modelNumber: 'FF-BAT-LNK-18',
    wattage: 18,
    lumens: 1980,
    efficacy: 110,
    cct: '6500K (Daylight)',
    cri: 80,
    mountingType: 'Surface / Under Cabinet',
    beamAngle: 120,
    utilizationFactor: 0.68,
    manufacturerReference: 'FF-BAT-LNK-18W',
    ipRating: 'IP20',
    dimensions: '1198x25x35 mm',
    typicalApplication: 'Residential garages, storage utility closets, continuous warehouse task benches',
    lifespan: '35,000 hrs',
    dimmable: 'No',
    description: 'Slimline rigid linkable batten with built-in gender couplers for seamless end-to-end cascading.'
  },

  // 39. LED Strip Lights
  {
    id: 'strip-high-density-12w',
    category: 'LED Strip Lights',
    lightType: 'High-Density Flexible LED Strip (12W/m)',
    wattageRange: '5W–18W',
    lumensRange: '500–1800 lm/m',
    brands: 'Omni, Akari, Custom Spec',
    manufacturer: 'Omni',
    modelNumber: 'OM-STRIP-HD-12',
    wattage: 12,
    lumens: 1200,
    efficacy: 100,
    cct: '3000K (Warm White)',
    cri: 90,
    mountingType: 'Adhesive / Surface',
    beamAngle: 120,
    utilizationFactor: 0.55,
    manufacturerReference: 'OM-STRIP-HD-12W',
    ipRating: 'IP65 (Silicone Coated)',
    dimensions: '5000x8x2 mm (Roll)',
    typicalApplication: 'Cove architectural pockets, custom furniture underlight accenting, stairway safety guides',
    lifespan: '30,000 hrs',
    dimmable: 'Yes (PWM / Low-Voltage)',
    description: 'High performance flexible linear strip populated with 120 LEDs per meter for smooth shadowless illumination.'
  },

  // 40. LED Tube Lights
  {
    id: 'tube-t8-glass-16w',
    category: 'LED Tube Lights',
    lightType: 'Double-Ended Glass LED T8 Tube (16W)',
    wattageRange: '10W–24W',
    lumensRange: '1000–2800 lm',
    brands: 'Philips, GE, Firefly',
    manufacturer: 'Philips',
    modelNumber: 'PH-TUBE-T8-16',
    wattage: 16,
    lumens: 1800,
    efficacy: 112.5,
    cct: '6500K (Daylight)',
    cri: 80,
    mountingType: 'G13 Lampholder Batten',
    beamAngle: 240,
    utilizationFactor: 0.70,
    manufacturerReference: 'PH-TUBE-T8-16W',
    ipRating: 'IP20',
    dimensions: '1200 mm Length',
    typicalApplication: 'Supermarket checkout rows, public administrative desks, basement garages',
    lifespan: '30,000 hrs',
    dimmable: 'No',
    description: 'Direct-wire double-ended glass retrofit LED tube replacing standard mercury-rich fluorescent lamps.'
  },

  // 41. LED Bulbs
  {
    id: 'bulb-high-power-30w',
    category: 'LED Bulbs',
    lightType: 'High-Power LED T-Bulb Lamp (30W)',
    wattageRange: '15W–45W',
    lumensRange: '1500–4500 lm',
    brands: 'Firefly, Omni, Akari',
    manufacturer: 'Firefly',
    modelNumber: 'FF-TB-30W-E27',
    wattage: 30,
    lumens: 3000,
    efficacy: 100,
    cct: '6500K (Daylight)',
    cri: 82,
    mountingType: 'E27 Screw Socket',
    beamAngle: 180,
    utilizationFactor: 0.65,
    manufacturerReference: 'FF-TB-30W',
    ipRating: 'IP20',
    dimensions: '100x180 mm',
    typicalApplication: 'High-ceiling residential salons, outdoor gate fixtures, industrial storage warehouses',
    lifespan: '25,000 hrs',
    dimmable: 'No',
    description: 'Heavy duty high lumen cylindrical T-shaped bulb providing broad radial area illumination.'
  },

  // 42. High Bay Lights
  {
    id: 'highbay-premium-200w',
    category: 'High Bay Lights',
    lightType: 'High-Efficacy UFO LED High Bay (200W)',
    wattageRange: '150W–240W',
    lumensRange: '20000–38000 lm',
    brands: 'GE Current, Philips, Lithonia',
    manufacturer: 'GE Current',
    modelNumber: 'GE-UFO-200W-HE',
    wattage: 200,
    lumens: 32000,
    efficacy: 160,
    cct: '5000K (Cool White)',
    cri: 80,
    mountingType: 'Hook / Suspended',
    beamAngle: 90,
    utilizationFactor: 0.85,
    manufacturerReference: 'GE-UFO-200W',
    ipRating: 'IP66',
    dimensions: '380x380x180 mm',
    typicalApplication: 'Industrial hangar bays, high ceiling distribution warehouses, sports complexes',
    lifespan: '100,000 hrs',
    dimmable: 'Yes (1-10V)',
    description: 'Heavy industrial UFO luminaire constructed from die-cast aluminum for extreme thermal dissipation.'
  },

  // 43. Low Bay Lights
  {
    id: 'lowbay-linear-90w',
    category: 'Low Bay Lights',
    lightType: 'Linear Heavy Duty LED Low Bay (90W)',
    wattageRange: '60W–120W',
    lumensRange: '8000–16000 lm',
    brands: 'Lithonia Lighting, Columbia, Omni',
    manufacturer: 'Lithonia Lighting',
    modelNumber: 'LBL-90W-IND',
    wattage: 90,
    lumens: 11700,
    efficacy: 130,
    cct: '4000K (Neutral White)',
    cri: 80,
    mountingType: 'Surface / Suspended',
    beamAngle: 110,
    utilizationFactor: 0.76,
    manufacturerReference: 'LT-LBL-90W',
    ipRating: 'IP54',
    dimensions: '600x300x70 mm',
    typicalApplication: 'Underground parking slots, industrial shop floors, bulk commercial supermarkets',
    lifespan: '70,000 hrs',
    dimmable: 'Yes',
    description: 'Wide beam optical low bay designed to deliver highly uniform horizontal lux in mid-height spaces.'
  },

  // 44. Flood Lights
  {
    id: 'flood-stadium-400w',
    category: 'Flood Lights',
    lightType: 'Professional Sports Stadium Floodlight (400W)',
    wattageRange: '250W–600W',
    lumensRange: '35000–85000 lm',
    brands: 'Cree Lighting, Philips, GE',
    manufacturer: 'Cree Lighting',
    modelNumber: 'CR-STAD-400',
    wattage: 400,
    lumens: 56000,
    efficacy: 140,
    cct: '5700K (Cool Daylight)',
    cri: 75,
    mountingType: 'Heavy-Duty Bracket',
    beamAngle: 45,
    utilizationFactor: 0.62,
    manufacturerReference: 'CR-STAD-400W',
    ipRating: 'IP66',
    dimensions: '520x450x120 mm',
    typicalApplication: 'Outdoor sports fields, major airport apron pads, heavy marine industrial zones',
    lifespan: '80,000 hrs',
    dimmable: 'Yes (DMX / 0-10V)',
    description: 'Precision flood projector featuring micro-lens arrays for low-glare asymmetric lighting.'
  },

  // 45. Street Lights
  {
    id: 'street-highway-150w',
    category: 'Street Lights',
    lightType: 'Smart Highway LED Streetlight (150W)',
    wattageRange: '100W–200W',
    lumensRange: '13000–26000 lm',
    brands: 'Philips, Ledvance, Omni',
    manufacturer: 'Philips',
    modelNumber: 'ROAD-150W-IP66',
    wattage: 150,
    lumens: 19500,
    efficacy: 130,
    cct: '4000K (Neutral White)',
    cri: 70,
    mountingType: 'Pole Arm Entry',
    beamAngle: 140,
    utilizationFactor: 0.54,
    manufacturerReference: 'PH-ROAD-150W',
    ipRating: 'IP66',
    dimensions: '680x310x120 mm',
    typicalApplication: 'High-speed motorways, major metropolitan intersections, logistics hub avenues',
    lifespan: '100,000 hrs',
    dimmable: 'Yes (NEMA Node Smart)',
    description: 'High efficacy outdoor luminaire with Type II-M optic distribution optimized for roadways.'
  },

  // 46. Area Lights
  {
    id: 'area-square-120w',
    category: 'Area Lights',
    lightType: 'Type III Square Parking Area Light (120W)',
    wattageRange: '80W–180W',
    lumensRange: '10000–24000 lm',
    brands: 'Lithonia Lighting, Cree, Custom Spec',
    manufacturer: 'Lithonia Lighting',
    modelNumber: 'AR-SQ-120',
    wattage: 120,
    lumens: 15600,
    efficacy: 130,
    cct: '5000K (Cool White)',
    cri: 70,
    mountingType: 'Pole slipfitter',
    beamAngle: 120,
    utilizationFactor: 0.58,
    manufacturerReference: 'LT-AR-SQ-120W',
    ipRating: 'IP66',
    dimensions: '350x350x95 mm',
    typicalApplication: 'Commercial shopping plazas, corporate office parks, university open-air hubs',
    lifespan: '100,000 hrs',
    dimmable: 'Yes',
    description: 'Shoebox layout post-top area luminaire designed with wide-throw dark-sky compliant optics.'
  },

  // 47. Wall Pack Lights
  {
    id: 'wallpack-semi-cutoff-45w',
    category: 'Wall Pack Lights',
    lightType: 'Semi-Cutoff LED Wall Pack (45W)',
    wattageRange: '30W–80W',
    lumensRange: '3500–9000 lm',
    brands: 'Hubbell Lighting, Columbia, Akari',
    manufacturer: 'Hubbell Lighting',
    modelNumber: 'HB-WP-45-SC',
    wattage: 45,
    lumens: 5400,
    efficacy: 120,
    cct: '4000K (Neutral White)',
    cri: 70,
    mountingType: 'Wall-mounted',
    beamAngle: 105,
    utilizationFactor: 0.52,
    manufacturerReference: 'HB-WP-45W-SC',
    ipRating: 'IP65',
    dimensions: '280x210x160 mm',
    typicalApplication: 'Loading dock loading doors, industrial alleys, secondary campus wall security',
    lifespan: '60,000 hrs',
    dimmable: 'No',
    description: 'Heavy duty architectural cast housing wallpack with optical prismatic borosilicate glass lens.'
  },

  // 48. Bollard Lights
  {
    id: 'bollard-flat-top-20w',
    category: 'Bollard Lights',
    lightType: 'Flat-Top Louvered Bollard Light (20W)',
    wattageRange: '10W–30W',
    lumensRange: '800–2400 lm',
    brands: 'Bega, Hubbell, Custom Spec',
    manufacturer: 'Bega',
    modelNumber: 'BG-BLD-FT-20',
    wattage: 20,
    lumens: 1600,
    efficacy: 80,
    cct: '3000K (Warm White)',
    cri: 80,
    mountingType: 'Ground / Flange mounted',
    beamAngle: 360,
    utilizationFactor: 0.38,
    manufacturerReference: 'BG-BLD-FT-20W',
    ipRating: 'IP65',
    dimensions: '180x180x900 mm',
    typicalApplication: 'Garden path walkways, high-profile hotel perimeter alleys, outdoor seating lounges',
    lifespan: '50,000 hrs',
    dimmable: 'Yes',
    description: 'Vandal resistant cylindrical aluminum ground bollard featuring internal light-directing deflectors.'
  },

  // 49. Garden Lights
  {
    id: 'garden-well-light-7w',
    category: 'Garden Lights',
    lightType: 'Recessed In-Ground LED Well Light (7W)',
    wattageRange: '3W–12W',
    lumensRange: '240–1000 lm',
    brands: 'Hinkley, Kichler, Bega',
    manufacturer: 'Hinkley',
    modelNumber: 'HK-WELL-7W',
    wattage: 7,
    lumens: 560,
    efficacy: 80,
    cct: '2700K (Very Warm)',
    cri: 85,
    mountingType: 'Recessed Concrete / Soil',
    beamAngle: 30,
    utilizationFactor: 0.42,
    manufacturerReference: 'HK-WELL-7W-IP67',
    ipRating: 'IP67',
    dimensions: '90x90x110 mm',
    typicalApplication: 'Tree canopy uplighting, dynamic exterior garden walls, landscape pathways',
    lifespan: '35,000 hrs',
    dimmable: 'No',
    description: 'Heavy capacity walk-over recessed well light featuring marine grade stainless steel trim.'
  },

  // 50. Landscape Lights
  {
    id: 'landscape-flood-15w',
    category: 'Landscape Lights',
    lightType: 'Compact Landscape Accent Spot Flood (15W)',
    wattageRange: '8W–25W',
    lumensRange: '600–2200 lm',
    brands: 'Kichler, Hinkley, Custom Spec',
    manufacturer: 'Kichler',
    modelNumber: 'KC-LAND-15W',
    wattage: 15,
    lumens: 1350,
    efficacy: 90,
    cct: '3000K (Warm White)',
    cri: 82,
    mountingType: 'Spike / Bracket Mounted',
    beamAngle: 35,
    utilizationFactor: 0.46,
    manufacturerReference: 'KC-LAND-15W-IP66',
    ipRating: 'IP66',
    dimensions: '110x85x145 mm',
    typicalApplication: 'Main building facade wash, landscape features, outdoor sculpture accents',
    lifespan: '40,000 hrs',
    dimmable: 'No',
    description: 'Knuckle-joint rotatable landscape projector engineered for direct outdoor landscape spotlighting.'
  },

  // 51. Pole Lights
  {
    id: 'pole-decorative-80w',
    category: 'Pole Lights',
    lightType: 'Decorative Post-Top Garden Pole Light (80W)',
    wattageRange: '50W–120W',
    lumensRange: '5000–13000 lm',
    brands: 'Bega, Hubbell, Philips',
    manufacturer: 'Bega',
    modelNumber: 'BG-PT-80W',
    wattage: 80,
    lumens: 8800,
    efficacy: 110,
    cct: '4000K (Neutral White)',
    cri: 80,
    mountingType: 'Post-Top Pole',
    beamAngle: 360,
    utilizationFactor: 0.48,
    manufacturerReference: 'BG-PT-80W-LED',
    ipRating: 'IP65',
    dimensions: '450x450x650 mm',
    typicalApplication: 'Parks, municipal pedestrian walkways, historical town square complexes',
    lifespan: '80,000 hrs',
    dimmable: 'Yes',
    description: 'Premium circular direct/indirect post-top architectural luminaire designed for glare-free garden zones.'
  },

  // 52. Canopy Lights
  {
    id: 'canopy-square-75w',
    category: 'Canopy Lights',
    lightType: 'Recessed Square Parking Canopy LED (75W)',
    wattageRange: '50W–100W',
    lumensRange: '6000–13000 lm',
    brands: 'GE Current, Philips, Omni',
    manufacturer: 'GE Current',
    modelNumber: 'CNP-SQ-75',
    wattage: 75,
    lumens: 9750,
    efficacy: 130,
    cct: '5000K (Cool White)',
    cri: 80,
    mountingType: 'Recessed / Surface',
    beamAngle: 110,
    utilizationFactor: 0.78,
    manufacturerReference: 'GE-CNP-SQ-75W',
    ipRating: 'IP65',
    dimensions: '300x300x65 mm',
    typicalApplication: 'Gas station underpasses, pedestrian walkways, hotel loading bays, garages',
    lifespan: '100,000 hrs',
    dimmable: 'No',
    description: 'Sealed low profile canopy fixture with premium frosted polycarbonate vandal-proof diffuser.'
  },

  // 53. Emergency Lights
  {
    id: 'emergency-lite-6w',
    category: 'Emergency Lights',
    lightType: 'Compact Recessed LED Emergency Spotlight (6W)',
    wattageRange: '3W–12W',
    lumensRange: '250–900 lm',
    brands: 'Firefly, Akari, Omni',
    manufacturer: 'Firefly',
    modelNumber: 'FF-EMG-REC-6',
    wattage: 6,
    lumens: 480,
    efficacy: 80,
    cct: '6000K (Cool White)',
    cri: 75,
    mountingType: 'Recessed',
    beamAngle: 85,
    utilizationFactor: 0.50,
    manufacturerReference: 'FF-EMG-REC-6W',
    ipRating: 'IP20',
    dimensions: '85x85x45 mm',
    typicalApplication: 'High-density commercial corridors, office egress pathways, public conference rooms',
    lifespan: '50,000 hrs',
    dimmable: 'No',
    description: 'Compact recessed backup luminaire with self-contained backup battery and automated health test indicators.'
  },

  // 54. Exit Signs
  {
    id: 'exitsign-recessed-green',
    category: 'Exit Signs',
    lightType: 'Premium Recessed Glass Plate Exit Sign',
    wattageRange: '2W–5W',
    lumensRange: '80–200 lm',
    brands: 'Omni, Akari, Firefly',
    manufacturer: 'Omni',
    modelNumber: 'OM-EXIT-REC-G',
    wattage: 3,
    lumens: 150,
    efficacy: 50,
    cct: 'Green LED Spectrum',
    cri: 70,
    mountingType: 'Recessed',
    beamAngle: 180,
    utilizationFactor: 0.40,
    manufacturerReference: 'OM-EXIT-REC-GRN',
    ipRating: 'IP20',
    dimensions: '310x35x190 mm',
    typicalApplication: 'High-rise office pathways, auditoriums, commercial banks, municipal offices',
    lifespan: '50,000 hrs',
    dimmable: 'No',
    description: 'Sleek architectural glass plate recessed exit light with battery backup and directional stickers.'
  },

  // 55. Bulkhead Lights
  {
    id: 'bulkhead-round-ip65-15w',
    category: 'Bulkhead Lights',
    lightType: 'Round IP65 Outdoor Bulkhead Light (15W)',
    wattageRange: '10W–24W',
    lumensRange: '900–2200 lm',
    brands: 'Akari, Omni, Firefly',
    manufacturer: 'Akari',
    modelNumber: 'AK-BLK-RND-15',
    wattage: 15,
    lumens: 1350,
    efficacy: 90,
    cct: '4000K (Neutral White)',
    cri: 80,
    mountingType: 'Surface (Wall/Ceiling)',
    beamAngle: 115,
    utilizationFactor: 0.60,
    manufacturerReference: 'AK-BLK-RND-15W',
    ipRating: 'IP65',
    dimensions: '220x220x70 mm',
    typicalApplication: 'Exterior stairs, industrial maritime pathways, building basement washrooms',
    lifespan: '30,000 hrs',
    dimmable: 'No',
    description: 'Impact resistant circular exterior bulkhead crafted with a polycarbonate cover and anti-corrosive body.'
  },

  // 56. Vapor Tight Fixtures
  {
    id: 'vaportight-linear-4ft-50w',
    category: 'Vapor Tight Fixtures',
    lightType: 'Heavy Duty Vapor Tight Linear LED (50W)',
    wattageRange: '35W–60W',
    lumensRange: '4000–8000 lm',
    brands: 'Ledvance, Columbia, Philips',
    manufacturer: 'Ledvance',
    modelNumber: 'LD-VT-4FT-50',
    wattage: 5,
    lumens: 6500,
    efficacy: 130,
    cct: '5000K (Cool White)',
    cri: 80,
    mountingType: 'Surface / Suspended',
    beamAngle: 120,
    utilizationFactor: 0.72,
    manufacturerReference: 'LD-VT-4FT-50W',
    ipRating: 'IP66',
    dimensions: '1220x105x90 mm',
    typicalApplication: 'Industrial car washes, meat food processing plants, commercial deep-freeze rooms',
    lifespan: '75,000 hrs',
    dimmable: 'Yes',
    description: 'Vapor-tight enclosed housing designed to resist moisture, extreme cold, dust, and washdowns.'
  },

  // 57. Explosion-Proof Fixtures
  {
    id: 'exploproof-ufo-120w',
    category: 'Explosion-Proof Fixtures',
    lightType: 'Class I Div 1 Explosion-Proof LED (120W)',
    wattageRange: '80W–150W',
    lumensRange: '10000–20000 lm',
    brands: 'Appleton, Emerson, Custom Spec',
    manufacturer: 'Appleton / Emerson',
    modelNumber: 'AP-EX-120W',
    wattage: 120,
    lumens: 15600,
    efficacy: 130,
    cct: '5000K (Cool White)',
    cri: 80,
    mountingType: 'Pendant / Ceiling Bracket',
    beamAngle: 110,
    utilizationFactor: 0.80,
    manufacturerReference: 'AP-EX-UFO-120W',
    ipRating: 'IP66 / NEMA 4X',
    dimensions: '350x350x300 mm',
    typicalApplication: 'Oil & gas refineries, hazardous chemical labs, grain silos, aircraft hangars',
    lifespan: '80,000 hrs',
    dimmable: 'No',
    description: 'Explosion-resistant copper-free aluminum casting designed to contain any internal combustion safety.'
  },

  // 58. Industrial Lighting Fixtures
  {
    id: 'industrial-tubular-ip69k-35w',
    category: 'Industrial Lighting Fixtures',
    lightType: 'IP69K Waterproof Tubular LED Luminaire (35W)',
    wattageRange: '24W–50W',
    lumensRange: '3000–6500 lm',
    brands: 'Bega, Ledvance, Custom Spec',
    manufacturer: 'Bega',
    modelNumber: 'BG-TUB-35W',
    wattage: 35,
    lumens: 4550,
    efficacy: 130,
    cct: '4000K (Neutral White)',
    cri: 85,
    mountingType: 'Surface / Pipe Clamp',
    beamAngle: 120,
    utilizationFactor: 0.74,
    manufacturerReference: 'BG-TUB-35W-IP69K',
    ipRating: 'IP69K',
    dimensions: '1180x75 mm (Tube)',
    typicalApplication: 'High pressure washdowns, intensive assembly production lines, railway platform halls',
    lifespan: '70,000 hrs',
    dimmable: 'Yes',
    description: 'Circular tubular clean-profile fixture engineered to withstand extreme high pressure washing jets.'
  },

  // 59. Clean Room Fixtures
  {
    id: 'cleanroom-iso5-panel-48w',
    category: 'Clean Room Fixtures',
    lightType: 'ISO 5 Clean Room Recessed Sealed Panel (48W)',
    wattageRange: '36W–60W',
    lumensRange: '4000–7200 lm',
    brands: 'Philips, Ledvance, Lithonia',
    manufacturer: 'Philips',
    modelNumber: 'CR-ISO5-48W',
    wattage: 48,
    lumens: 5760,
    efficacy: 120,
    cct: '5000K (Cool White)',
    cri: 90,
    mountingType: 'Recessed Tee-Grid',
    beamAngle: 110,
    utilizationFactor: 0.75,
    manufacturerReference: 'PH-CR-ISO5-48W',
    ipRating: 'IP65',
    dimensions: '1195x595x55 mm',
    typicalApplication: 'Pharmaceutical laboratories, silicon microelectronics factories, hospital surgeries',
    lifespan: '60,000 hrs',
    dimmable: 'Yes (0-10V)',
    description: 'Recessed flat grid panel with wipe-down antimicrobial gaskets preventing particulate ingress.'
  },

  // 60. Pendant Lights
  {
    id: 'pendant-cone-concrete-10w',
    category: 'Pendant Lights',
    lightType: 'Concrete Cone LED Pendant (10W)',
    wattageRange: '5W–15W',
    lumensRange: '400–1200 lm',
    brands: 'Custom Decorative, Kichler',
    manufacturer: 'Custom Decorative',
    modelNumber: 'DEC-CONE-C10',
    wattage: 10,
    lumens: 800,
    efficacy: 80,
    cct: '2700K (Soft Warm)',
    cri: 95,
    mountingType: 'Suspended (Pendant)',
    beamAngle: 60,
    utilizationFactor: 0.54,
    manufacturerReference: 'CD-DEC-CONE-10W',
    ipRating: 'IP20',
    dimensions: '180x180x250 mm',
    typicalApplication: 'Dining bars, kitchen focal islands, design hospitality lobbies',
    lifespan: '30,000 hrs',
    dimmable: 'Yes (TRIAC)',
    description: 'Handcrafted concrete pendant fixture blending organic architectural textures with warm downlight.'
  },

  // 61. Chandelier Fixtures
  {
    id: 'chandelier-modern-sphere-80w',
    category: 'Chandelier Fixtures',
    lightType: 'Multi-Sphere Geometric Brass Chandelier (80W)',
    wattageRange: '60W–120W',
    lumensRange: '4500–9600 lm',
    brands: 'Custom Decorative, Philips',
    manufacturer: 'Custom Decorative',
    modelNumber: 'DEC-SPH-BR80',
    wattage: 80,
    lumens: 6400,
    efficacy: 80,
    cct: '2700K (Soft Warm)',
    cri: 92,
    mountingType: 'Suspended (Rigid Stem)',
    beamAngle: 360,
    utilizationFactor: 0.42,
    manufacturerReference: 'CD-DEC-SPH-BR80',
    ipRating: 'IP20',
    dimensions: '1000x1000x850 mm',
    typicalApplication: 'Atrium double-height hotel lobbies, executive dining spaces, grand residences',
    lifespan: '40,000 hrs',
    dimmable: 'Yes (TRIAC)',
    description: 'Designer geometric chandelier hosting 12 sandblasted milk glass globes for diffuse luxury lighting.'
  },

  // 62. Ceiling Mounted Fixtures
  {
    id: 'ceiling-drum-fabric-24w',
    category: 'Ceiling Mounted Fixtures',
    lightType: 'Fabric Drum Ceiling Flush Mount (24W)',
    wattageRange: '15W–36W',
    lumensRange: '1200–3200 lm',
    brands: 'Kichler, Columbia, Custom Spec',
    manufacturer: 'Kichler',
    modelNumber: 'KC-DRUM-FAB-24',
    wattage: 24,
    lumens: 2160,
    efficacy: 90,
    cct: '3000K (Warm White)',
    cri: 90,
    mountingType: 'Ceiling Flush Mount',
    beamAngle: 150,
    utilizationFactor: 0.58,
    manufacturerReference: 'KC-DRUM-FAB-24W',
    ipRating: 'IP20',
    dimensions: '400x400x120 mm',
    typicalApplication: 'Residential guest bedrooms, cozy hotel rooms, corridors',
    lifespan: '30,000 hrs',
    dimmable: 'Yes',
    description: 'Double linen fabric shade drum fixture with an integrated diffuser for soft ambient bedroom glow.'
  },

  // 63. Wall Sconces
  {
    id: 'wallsconce-updown-brass-12w',
    category: 'Wall Sconces',
    lightType: 'Up/Down Architectural Wall Sconce (12W)',
    wattageRange: '8W–18W',
    lumensRange: '600–1500 lm',
    brands: 'Bega, Custom Decorative, Omni',
    manufacturer: 'Bega',
    modelNumber: 'BG-SCONCE-12',
    wattage: 12,
    lumens: 960,
    efficacy: 80,
    cct: '2700K (Soft Warm)',
    cri: 90,
    mountingType: 'Wall-mounted',
    beamAngle: 95,
    utilizationFactor: 0.48,
    manufacturerReference: 'BG-SCONCE-12W-BR',
    ipRating: 'IP44',
    dimensions: '100x120x240 mm',
    typicalApplication: 'Premium hotel elevators, executive corporate corridors, luxury master bed heads',
    lifespan: '40,000 hrs',
    dimmable: 'Yes',
    description: 'Bilateral dual projection up-and-down wall sconce encased in brushed metallic brass.'
  },

  // 64. Under Cabinet Lights
  {
    id: 'undercabinets-rigid-30cm-6w',
    category: 'Under Cabinet Lights',
    lightType: 'Slim High-CRI Under Cabinet Bar (6W)',
    wattageRange: '4W–12W',
    lumensRange: '350–1000 lm',
    brands: 'Omni, Philips, Firefly',
    manufacturer: 'Omni',
    modelNumber: 'OM-UC-30-6W',
    wattage: 6,
    lumens: 540,
    efficacy: 90,
    cct: '3000K (Warm White)',
    cri: 95,
    mountingType: 'Surface (Adhesive/Screws)',
    beamAngle: 110,
    utilizationFactor: 0.60,
    manufacturerReference: 'OM-UC-30-6W-CRI95',
    ipRating: 'IP20',
    dimensions: '300x25x10 mm',
    typicalApplication: 'Kitchen prep counters, retail jewelry glass cases, dental workbench stations',
    lifespan: '40,000 hrs',
    dimmable: 'Yes',
    description: 'Ultra slim low voltage cabinet fixture optimized with high fidelity color rendering chips.'
  },

  // 65. Cove Lighting Fixtures
  {
    id: 'cove-rigid-seamless-15w',
    category: 'Cove Lighting Fixtures',
    lightType: 'Rigid Seamless Linkable Cove Strip (15W/m)',
    wattageRange: '8W–20W',
    lumensRange: '800–2000 lm/m',
    brands: 'Philips, Ledvance, Custom Spec',
    manufacturer: 'Philips',
    modelNumber: 'PH-COVE-RIG-15',
    wattage: 15,
    lumens: 1500,
    efficacy: 100,
    cct: '3000K (Warm White)',
    cri: 90,
    mountingType: 'Surface / Cove Track',
    beamAngle: 120,
    utilizationFactor: 0.64,
    manufacturerReference: 'PH-COVE-RIG-15W',
    ipRating: 'IP20',
    dimensions: '1000x20x15 mm',
    typicalApplication: 'Architectural coffered tray ceilings, wall wash false ceiling recess borders',
    lifespan: '50,000 hrs',
    dimmable: 'Yes (Phase Cut)',
    description: 'Slim rigid extrusion with integrated interlocking connectors ensuring shadowless seamless line joins.'
  },

  // 66. Architectural Lighting Fixtures
  {
    id: 'architectural-curved-ring-60w',
    category: 'Architectural Lighting Fixtures',
    lightType: 'Minimalist Curved Ring Profile Luminaire (60W)',
    wattageRange: '40W–90W',
    lumensRange: '3600–8500 lm',
    brands: 'Ledvance, Philips, Custom Spec',
    manufacturer: 'Ledvance',
    modelNumber: 'LD-RING-ARC-60',
    wattage: 60,
    lumens: 5400,
    efficacy: 90,
    cct: '4000K (Neutral White)',
    cri: 90,
    mountingType: 'Suspended (Pendant)',
    beamAngle: 140,
    utilizationFactor: 0.65,
    manufacturerReference: 'LD-RING-ARC-60W',
    ipRating: 'IP20',
    dimensions: '1200 mm Diameter',
    typicalApplication: 'Modern creative design studios, public lounge areas, grand open atriums',
    lifespan: '60,000 hrs',
    dimmable: 'Yes',
    description: 'Circular continuous ring architectural pendant light with inside and downward light throw.'
  },

  // 67. Decorative Lighting Fixtures
  {
    id: 'decorative-honeycomb-hex-45w',
    category: 'Decorative Lighting Fixtures',
    lightType: 'Hexagonal Honeycomb Modular LED (45W)',
    wattageRange: '30W–60W',
    lumensRange: '2500–5500 lm',
    brands: 'Custom Decorative, Akari',
    manufacturer: 'Custom Decorative',
    modelNumber: 'DEC-HEX-MOD-45',
    wattage: 45,
    lumens: 4050,
    efficacy: 90,
    cct: '4000K (Neutral White)',
    cri: 88,
    mountingType: 'Suspended / Surface',
    beamAngle: 115,
    utilizationFactor: 0.66,
    manufacturerReference: 'CD-DEC-HEX-45W',
    ipRating: 'IP20',
    dimensions: '800x700x50 mm',
    typicalApplication: 'Co-working office clusters, creative studio ceilings, high tech gaming centers',
    lifespan: '45,000 hrs',
    dimmable: 'Yes',
    description: 'Unique geometric modular honeycomb grid lighting array delivering balanced direct distribution.'
  },

  // 68. Solar-Powered Lighting Fixtures
  {
    id: 'solar-flood-heavy-100w',
    category: 'Solar-Powered Lighting Fixtures',
    lightType: 'All-in-Two Solar Commercial Floodlight (100W)',
    wattageRange: '50W–150W',
    lumensRange: '7000–21000 lm',
    brands: 'Custom-Green, Akari, Bega',
    manufacturer: 'Custom-Green',
    modelNumber: 'SG-FL-SOL-100',
    wattage: 100,
    lumens: 14000,
    efficacy: 140,
    cct: '6000K (Cool White)',
    cri: 70,
    mountingType: 'Surface (Yoke)',
    beamAngle: 120,
    utilizationFactor: 0.55,
    manufacturerReference: 'SG-FL-SOL-100W',
    ipRating: 'IP67',
    dimensions: '320x260x85 mm',
    typicalApplication: 'Grid isolated parking perimeters, security perimeter fences, remote agricultural yards',
    lifespan: '50,000 hrs',
    dimmable: 'No',
    description: 'Completely off-grid solar spotlight pairing high efficiency monocrystalline solar panels with Lifepo4 battery storage.'
  }
];

export const INITIAL_ILLUMINATION_PARAMS: IlluminationParams = {
  inputMode: 'dimensions',
  roomName: 'Office Room 1',
  roomType: 'General Office',
  roomWidth: 4,
  roomLength: 5,
  userArea: 20,
  ceilingHeight: 2.7,
  workingPlaneHeight: 0.75,
  mountingHeight: 1.95,
  targetLux: 500, // Default to a standard office lux
  selectedFixtureId: 'ind-panel',
  lumensPerFixture: 3600,
  coefficientOfUtilization: 0.6,
  maintenanceFactor: 0.8,
  ceilingReflectance: 0.7,
  wallReflectance: 0.5,
  floorReflectance: 0.2,
  electricityRate: 11.5,
  operatingHoursDaily: 10
};

export const DESCRIPTION_CODES = {
  L: 'Lighting',
  S: 'Socket Outlets',
  AC: 'Air Conditioning',
  M: 'Motors / Pumps',
  P: 'Power',
  SP: 'Spare',
  SPACE: 'Space',
  SUB: 'Sub-Panel',
  SUBSUB: 'Sub-Sub Panel',
};

export const CONDUIT_SIZES = ['15mm', '20mm', '25mm', '32mm', '40mm', '50mm', '65mm', '80mm', '90mm', '100mm'];

export const CONDUIT_LIBRARY: Record<string, { size: string, limit: number }[]> = {
  PVC: [
    { size: "15mm", limit: 78 },
    { size: "20mm", limit: 137 },
    { size: "25mm", limit: 220 },
    { size: "32mm", limit: 380 },
    { size: "40mm", limit: 518 },
    { size: "50mm", limit: 855 },
    { size: "65mm", limit: 1220 },
    { size: "80mm", limit: 1880 },
    { size: "90mm", limit: 2500 },
    { size: "100mm", limit: 3240 },
  ],
  EMT: [
    { size: "15mm", limit: 98 },
    { size: "20mm", limit: 163 },
    { size: "25mm", limit: 262 },
    { size: "32mm", limit: 450 },
    { size: "40mm", limit: 610 },
    { size: "50mm", limit: 1000 },
    { size: "65mm", limit: 1620 },
    { size: "80mm", limit: 2210 },
    { size: "90mm", limit: 2920 },
    { size: "100mm", limit: 3800 },
  ],
  RSC: [
    { size: "15mm", limit: 82 },
    { size: "20mm", limit: 141 },
    { size: "25mm", limit: 228 },
    { size: "32mm", limit: 396 },
    { size: "40mm", limit: 540 },
    { size: "50mm", limit: 890 },
    { size: "65mm", limit: 1270 },
    { size: "80mm", limit: 1960 },
    { size: "90mm", limit: 2610 },
    { size: "100mm", limit: 3400 },
  ],
  IMC: [
    { size: "15mm", limit: 91 },
    { size: "20mm", limit: 154 },
    { size: "25mm", limit: 249 },
    { size: "32mm", limit: 428 },
    { size: "40mm", limit: 581 },
    { size: "50mm", limit: 955 },
    { size: "65mm", limit: 1440 },
    { size: "80mm", limit: 2230 },
    { size: "90mm", limit: 2980 },
    { size: "100mm", limit: 3870 },
  ],
  FMC: [
    { size: "15mm", limit: 80 },
    { size: "20mm", limit: 135 },
    { size: "25mm", limit: 222 },
    { size: "32mm", limit: 385 },
    { size: "40mm", limit: 520 },
    { size: "50mm", limit: 858 },
    { size: "65mm", limit: 1230 },
    { size: "80mm", limit: 1890 },
    { size: "90mm", limit: 2510 },
    { size: "100mm", limit: 3260 },
  ],
  "Flexible Conduit": [
    { size: "15mm", limit: 80 },
    { size: "20mm", limit: 135 },
    { size: "25mm", limit: 222 },
    { size: "32mm", limit: 385 },
    { size: "40mm", limit: 520 },
    { size: "50mm", limit: 858 },
    { size: "65mm", limit: 1230 },
    { size: "80mm", limit: 1890 },
    { size: "90mm", limit: 2510 },
    { size: "100mm", limit: 3260 },
  ],
};

// PEC Table 9 (Resistance and Reactance for 600V Cables)
// Values in Ohms per 1000m (or Ohm/km)
export const WIRE_IMPEDANCE_TABLE: Record<string, { r: number, x: number }> = {
  '2.0': { r: 10.15, x: 0.164 },
  '3.5': { r: 5.76, x: 0.157 },
  '5.5': { r: 3.61, x: 0.148 },
  '8.0': { r: 2.27, x: 0.144 },
  '14': { r: 1.30, x: 0.141 },
  '22': { r: 0.817, x: 0.135 },
  '30': { r: 0.587, x: 0.135 },
  '38': { r: 0.463, x: 0.131 },
  '50': { r: 0.354, x: 0.128 },
  '60': { r: 0.282, x: 0.128 },
  '80': { r: 0.223, x: 0.125 },
  '100': { r: 0.177, x: 0.125 },
  '125': { r: 0.141, x: 0.121 },
  '150': { r: 0.118, x: 0.121 },
  '175': { r: 0.108, x: 0.118 },
  '200': { r: 0.089, x: 0.115 },
  '250': { r: 0.072, x: 0.112 },
  '325': { r: 0.055, x: 0.108 },
  '375': { r: 0.048, x: 0.105 },
  '400': { r: 0.045, x: 0.102 },
  '500': { r: 0.036, x: 0.098 },
};

export const RECOMMENDED_LUX_LEVELS_CATEGORIZED: Record<string, { name: string; lux: number }[]> = {
  "Residential Lighting": [
    { name: "Living Room", lux: 150 },
    { name: "Bedroom", lux: 200 },
    { name: "Kitchen (General)", lux: 300 },
    { name: "Kitchen (Task)", lux: 500 },
    { name: "Bathroom (General)", lux: 200 },
    { name: "Bathroom (Mirror)", lux: 500 },
    { name: "Hallways / Stairs", lux: 100 },
    { name: "Dining Area", lux: 200 },
  ],
  "Office & Educational": [
    { name: "General Office", lux: 500 },
    { name: "Workstations", lux: 500 },
    { name: "Meeting Rooms", lux: 500 },
    { name: "Reading / Study", lux: 500 },
    { name: "CAD / Drafting", lux: 750 },
    { name: "Classrooms", lux: 500 },
    { name: "Libraries", lux: 500 },
  ],
  "Commercial & Retail": [
    { name: "Small Shops", lux: 500 },
    { name: "Supermarkets", lux: 750 },
    { name: "Showrooms", lux: 750 },
    { name: "Display / Feature Areas", lux: 2000 },
    { name: "Reception", lux: 300 },
  ],
  "Industrial": [
    { name: "Warehouses", lux: 100 },
    { name: "Packing / Sorting", lux: 300 },
    { name: "Mechanical Rooms", lux: 150 },
    { name: "Heavy Industrial Work", lux: 500 },
    { name: "Precision Work / Inspection", lux: 2000 },
  ],
  "Public Areas": [
    { name: "Corridors", lux: 150 },
    { name: "Stairwells", lux: 100 },
    { name: "Lobbies", lux: 200 },
    { name: "Parking Areas", lux: 150 },
    { name: "Outdoor Walkways", lux: 40 },
  ],
  "Healthcare": [
    { name: "Patient Rooms", lux: 200 },
    { name: "Examination Rooms", lux: 1000 },
    { name: "Operating Rooms", lux: 1500 },
  ]
};

export const RECOMMENDED_LUX_LEVELS: Record<string, number> = {};
Object.entries(RECOMMENDED_LUX_LEVELS_CATEGORIZED).forEach(([_, items]) => {
  items.forEach(item => {
    RECOMMENDED_LUX_LEVELS[item.name] = item.lux;
  });
});


export interface LoadPreset {
  category: string;
  items: {
    description: string;
    wattage: number;
    loadType: string;
    label: string;
  }[];
}

export const LOAD_PRESETS: LoadPreset[] = [
  {
    category: "Lighting Loads",
    items: [
      { description: "LED Bulb", wattage: 10, loadType: "L", label: "LED Bulb (5W – 18W)" },
      { description: "Fluorescent Lamp", wattage: 30, loadType: "L", label: "Fluorescent Lamp (18W – 40W)" },
      { description: "LED Tube Light", wattage: 16, loadType: "L", label: "LED Tube Light (9W – 24W)" },
      { description: "CFL Lamp", wattage: 20, loadType: "L", label: "CFL Lamp (12W – 26W)" },
      { description: "Chandelier", wattage: 150, loadType: "L", label: "Chandelier (40W – 300W)" },
      { description: "Emergency Light", wattage: 10, loadType: "L", label: "Emergency Light (5W – 20W)" },
      { description: "Flood Light", wattage: 250, loadType: "L", label: "Flood Light (50W – 500W)" },
      { description: "Street Light", wattage: 150, loadType: "L", label: "Street Light (50W – 250W)" },
      { description: "Exit Sign Light", wattage: 5, loadType: "L", label: "Exit Sign Light (3W – 10W)" },
      { description: "Industrial High-Bay LED", wattage: 150, loadType: "L", label: "High-Bay LED (100W – 300W)" },
      { description: "Industrial Low-Bay LED", wattage: 80, loadType: "L", label: "Low-Bay LED (60W – 120W)" },
      { description: "Commercial Track Light System", wattage: 120, loadType: "L", label: "Track Light Array (50W – 300W)" },
      { description: "Office LED Panel Light 600x600", wattage: 40, loadType: "L", label: "LED Flat Panel (24W – 60W)" },
      { description: "Recessed LED Downlight", wattage: 12, loadType: "L", label: "Recessed Ceiling Downlight (6W – 24W)" },
      { description: "Metal Halide HID Fixture", wattage: 400, loadType: "L", label: "High-Intensity Discharge (150W – 1000W)" },
      { description: "High-Pressure Sodium Lamp", wattage: 250, loadType: "L", label: "HPS Street/Industrial Lamp (70W – 400W)" },
      { description: "Architectural LED Wall Washer", wattage: 60, loadType: "L", label: "LED Flood/Façade Light (30W – 150W)" },
      { description: "Specialized Surgical Light", wattage: 300, loadType: "L", label: "Operating Room Surgical Luminaire" },
      { description: "Landscape LED Spotlight", wattage: 15, loadType: "L", label: "Outdoor Accent Spotlight (5W – 30W)" },
      { description: "High-Power Sports Floodlight Array", wattage: 1000, loadType: "L", label: "Stadium Sports LED (600W – 2000W)" }
    ]
  },
  {
    category: "Convenience Outlet Loads",
    items: [
      { description: "Convenience Outlet", wattage: 180, loadType: "S", label: "Convenience Outlet (General Purpose) (180W p/outlet)" },
      { description: "Dedicated Outlet", wattage: 1000, loadType: "S", label: "Dedicated Outlet (500W – 2000W)" },
      { description: "USB Outlet", wattage: 40, loadType: "S", label: "USB Outlet (15W – 65W)" },
      { description: "GFCI Wet Area Outlet", wattage: 180, loadType: "S", label: "Wet Area GFCI Protection (180W, 1Ø)" },
      { description: "Industrial Single-Phase 20A Outlet", wattage: 1500, loadType: "S", label: "Heavy Duty Twist-Lock Outlet (1Ø)" },
      { description: "Industrial Three-Phase 30A Outlet", wattage: 3600, loadType: "S", label: "Heavy Duty Power Outlet (3Ø)" },
      { description: "Floor Convenience Outlet Box", wattage: 360, loadType: "S", label: "Duplex Floor Mounted Receptacle (1Ø)" },
      { description: "Multiplex Office Desk Outlet Assembly", wattage: 720, loadType: "S", label: "Quad Desk-Integrated Power Strip (1Ø)" },
      { description: "Isolated Ground Receptacle", wattage: 180, loadType: "S", label: "Clean Ground PC / Direct IT Equipment (1Ø)" },
      { description: "Utility Shop Receptacle", wattage: 1800, loadType: "S", label: "Workshop Heavy Outlet (1000W – 2500W, 1Ø)" }
    ]
  },
  {
    category: "Kitchen Appliances",
    items: [
      { description: "Refrigerator", wattage: 500, loadType: "S", label: "Refrigerator (150W – 800W)" },
      { description: "Microwave Oven", wattage: 1200, loadType: "S", label: "Microwave Oven (800W – 1500W)" },
      { description: "Rice Cooker", wattage: 800, loadType: "S", label: "Rice Cooker (500W – 1200W)" },
      { description: "Electric Stove", wattage: 3000, loadType: "P", label: "Electric Stove (1000W – 5000W)" },
      { description: "Induction Cooker", wattage: 2000, loadType: "P", label: "Induction Cooker (1200W – 3500W)" },
      { description: "Oven", wattage: 3000, loadType: "P", label: "Oven (1000W – 5000W)" },
      { description: "Toaster", wattage: 1000, loadType: "S", label: "Toaster (600W – 1500W)" },
      { description: "Blender", wattage: 500, loadType: "S", label: "Blender (300W – 1000W)" },
      { description: "Coffee Maker", wattage: 1000, loadType: "S", label: "Coffee Maker (600W – 1500W)" },
      { description: "Water Dispenser", wattage: 500, loadType: "S", label: "Water Dispenser (300W – 800W)" },
      { description: "Range Hood", wattage: 200, loadType: "M", label: "Range Hood (100W – 300W)" },
      { description: "Commercial Deep Fryer", wattage: 5000, loadType: "P", label: "Heavy Duty Kitchen Fryer (4kW – 9kW, 1Ø/3Ø)" },
      { description: "Espresso Machine (Commercial)", wattage: 3500, loadType: "P", label: "Multi-Headed Espresso Station (2kW – 6kW)" },
      { description: "Automatic Dishwasher", wattage: 1500, loadType: "P", label: "Kitchen Sanitary Dishwasher (1200W – 2500W)" },
      { description: "Garbage Disposal Unit - 0.5 HP", wattage: 600, loadType: "M", label: "Food Waste Disposer (300W – 900W)" },
      { description: "Commercial Electric Griddle", wattage: 1500, loadType: "P", label: "Countertop Griddle Surface (1kW – 3kW)" },
      { description: "Walk-in Refrigerator/Freezer System", wattage: 3000, loadType: "P", label: "Commercial Storage Cold Room Unit (1.5kW – 5kW)" },
      { description: "Commercial Conveyor Toaster", wattage: 2400, loadType: "P", label: "High Volume Conveyor Toaster (1.5kW – 3.6kW)" },
      { description: "Commercial Ice Maker", wattage: 1200, loadType: "P", label: "Automatic Bulk Ice Dispenser (800W – 2000W)" }
    ]
  },
  {
    category: "Air Conditioning (PEC 2017 Based)",
    items: [
      { description: "Window Type ACU - 0.5 HP", wattage: 1127, loadType: "AC", label: "4.9A FLC @ 230V" },
      { description: "Window Type ACU - 0.75 HP", wattage: 1587, loadType: "AC", label: "6.9A FLC @ 230V" },
      { description: "Window/Split ACU - 1.0 HP", wattage: 1840, loadType: "AC", label: "8.0A FLC @ 230V" },
      { description: "Split Type ACU - 1.5 HP", wattage: 2300, loadType: "AC", label: "10.0A FLC @ 230V" },
      { description: "Split Type ACU - 2.0 HP", wattage: 2760, loadType: "AC", label: "12.0A FLC @ 230V" },
      { description: "Split Type ACU - 2.5 HP", wattage: 3450, loadType: "AC", label: "15.0A FLC @ 230V" },
      { description: "Package ACU - 3.0 HP", wattage: 3910, loadType: "AC", label: "17.0A FLC @ 230V" },
      { description: "Floor Mounted ACU - 4.0 HP", wattage: 5060, loadType: "AC", label: "22.0A FLC @ 230V" },
      { description: "Centralized ACU - 5.0 HP", wattage: 6440, loadType: "AC", label: "28.0A FLC @ 230V" },
      { description: "Central Chiller Unit - 7.5 HP", wattage: 9200, loadType: "AC", label: "Medium Chiller System (25.3A FLC @ 230V 3Ø)" },
      { description: "Central Chiller Unit - 10 HP", wattage: 11500, loadType: "AC", label: "Large Chiller System (32.2A FLC @ 230V 3Ø)" },
      { description: "VRF Outdoor Heat Pump - 15 HP", wattage: 16100, loadType: "AC", label: "VRF Multizone System (46.0A FLC @ 230V 3Ø)" },
      { description: "VRF Outdoor Heat Pump - 20 HP", wattage: 21600, loadType: "AC", label: "High-Capacity VRF System (62.0A FLC @ 230V 3Ø)" },
      { description: "Precision CRAC Unit - 3.0 HP", wattage: 3910, loadType: "AC", label: "Data Center ACU (17.0A FLC @ 230V 1Ø/3Ø)" },
      { description: "Precision CRAC Unit - 5.0 HP", wattage: 6440, loadType: "AC", label: "Data Center ACU (28.0A FLC @ 230V 3Ø)" },
      { description: "Multi-Split Inverter OD Unit - 4.5 HP", wattage: 5800, loadType: "AC", label: "Multi-Zone Residential Inverter (3Ø)" }
    ]
  },
  {
    category: "Water & Pumping System",
    items: [
      { description: "Water Pump", wattage: 746, loadType: "M", label: "Water Pump (0.5HP – 5HP)" },
      { description: "Deep Well Pump", wattage: 1492, loadType: "M", label: "Deep Well Pump (1HP – 10HP)" },
      { description: "Sewage Pump", wattage: 1492, loadType: "M", label: "Sewage Pump (1HP – 15HP)" },
      { description: "Pressure Pump", wattage: 746, loadType: "M", label: "Pressure Pump (0.5HP – 3HP)" },
      { description: "Fire Jockey Pump - 2 HP", wattage: 2760, loadType: "M", label: "System Jockey Pressure Pump (1Ø/3Ø)" },
      { description: "Fire Main Pump - 15 HP", wattage: 17250, loadType: "M", label: "Main Fire Suppression Pump (3Ø)" },
      { description: "Agricultural Irrigation Pump - 5 HP", wattage: 6440, loadType: "M", label: "Large High-Lift Water Pump (3Ø)" },
      { description: "Swimming Pool Circulation Pump - 1.5 HP", wattage: 2300, loadType: "M", label: "Circulation & Filtration Motor (1Ø)" },
      { description: "Submersible Drainage Sump Pump - 0.75 HP", wattage: 1587, loadType: "M", label: "Automatic Submersible Chamber Sump Pump (1Ø)" },
      { description: "HVAC Chilled Water Pump - 3 HP", wattage: 3910, loadType: "M", label: "HVAC Closed-Loop In-line Circulator (3Ø)" }
    ]
  },
  {
    category: "Laundry & Cleaning Equipment",
    items: [
      { description: "Washing Machine", wattage: 800, loadType: "M", label: "Washing Machine (400W – 1500W)" },
      { description: "Dryer", wattage: 3000, loadType: "P", label: "Dryer (1500W – 5000W)" },
      { description: "Vacuum Cleaner", wattage: 1000, loadType: "S", label: "Vacuum Cleaner (500W – 2000W)" },
      { description: "Electric Iron", wattage: 1000, loadType: "S", label: "Electric Iron (700W – 2000W)" },
      { description: "Commercial Washing Extractor", wattage: 4500, loadType: "P", label: "Industrial Grade Laundry Extractor (3kW – 6kW)" },
      { description: "Multi-Headed Steam Press", wattage: 4000, loadType: "P", label: "Laundry Facility Steam Press Station (2.5kW – 5kW)" },
      { description: "Central Vacuum Cleaning System", wattage: 2200, loadType: "M", label: "Whole-House Vacuum Suction Unit" },
      { description: "Commercial Heat Pump Clothes Dryer", wattage: 6000, loadType: "P", label: "Industrial Tumble Dryer Unit (4.5kW – 9kW)" },
      { description: "Ultrasonic Cleaning Basin", wattage: 800, loadType: "S", label: "Precision Surgical/Industrial Ultrasonic Cleaner" }
    ]
  },
  {
    category: "Entertainment & Office Loads",
    items: [
      { description: "Television", wattage: 150, loadType: "S", label: "Television (50W – 400W)" },
      { description: "Desktop Computer", wattage: 300, loadType: "S", label: "Desktop Computer (150W – 750W)" },
      { description: "Laptop Charger", wattage: 65, loadType: "S", label: "Laptop Charger (45W – 180W)" },
      { description: "Printer", wattage: 200, loadType: "S", label: "Printer (100W – 1000W)" },
      { description: "Wi-Fi Router", wattage: 15, loadType: "S", label: "Wi-Fi Router (10W – 30W)" },
      { description: "CCTV System", wattage: 100, loadType: "S", label: "CCTV System (50W – 300W)" },
      { description: "Sound System", wattage: 500, loadType: "S", label: "Sound System (100W – 2000W)" },
      { description: "Network PoE Switch 48-Port", wattage: 500, loadType: "S", label: "Managed Power-over-Ethernet Unit" },
      { description: "Enterprise Rack Server", wattage: 800, loadType: "S", label: "1U-4U Standard Rack Server Box" },
      { description: "Enterprise Multi-Function Copier", wattage: 1500, loadType: "S", label: "Commercial Network Plotter & Copier" },
      { description: "Conference Hall Laser Projector", wattage: 400, loadType: "L", label: "Projector Luminaire (200W – 600W)" },
      { description: "Lobby LED Video Wall", wattage: 2500, loadType: "L", label: "Modular Composite Video Panel (1kW – 5kW)" },
      { description: "Smart UPS Float Charger", wattage: 1500, loadType: "S", label: "Uninterruptible Power Supply Main Charger Panel" },
      { description: "Point of Sale (POS) Workstation", wattage: 150, loadType: "S", label: "Retail Register, Terminal, Printer Assembly" }
    ]
  },
  {
    category: "Bathroom Loads",
    items: [
      { description: "Water Heater", wattage: 3000, loadType: "P", label: "Water Heater (1500W – 6000W)" },
      { description: "Hair Dryer", wattage: 1500, loadType: "S", label: "Hair Dryer (800W – 2000W)" },
      { description: "Electric Shower Heater", wattage: 4500, loadType: "P", label: "Electric Shower Heater (3500W – 6500W)" },
      { description: "High-Speed Hand Dryer", wattage: 1800, loadType: "S", label: "Jet Airblade Restroom Hand Dryer" },
      { description: "Restroom Inline Exhaust Fan", wattage: 50, loadType: "M", label: "Ceiling Mechanical Exhaust (20W – 100W)" },
      { description: "Whirlpool Jacuzzi Jet Pump - 1 HP", wattage: 1840, loadType: "M", label: "Bathtub Hydro-massage Water Jet Pump (1Ø)" },
      { description: "Heated Towel Rail", wattage: 150, loadType: "S", label: "Restroom Towel Dehumidifier / Warmer Rack" },
      { description: "Smart LED Vanity Mirror", wattage: 60, loadType: "L", label: "Vanity Mirror Defogger & Integrated Lighting" }
    ]
  },
  {
    category: "Motor Loads (PEC 2017 Based)",
    items: [
      { description: "Fan Motor - 1/6 HP", wattage: 506, loadType: "M", label: "2.2A FLC @ 230V" },
      { description: "Small Motor - 1/4 HP", wattage: 667, loadType: "M", label: "2.9A FLC @ 230V" },
      { description: "Small Motor - 1/3 HP", wattage: 828, loadType: "M", label: "3.6A FLC @ 230V" },
      { description: "Medium Motor - 1/2 HP", wattage: 1127, loadType: "M", label: "4.9A FLC @ 230V" },
      { description: "Medium Motor - 3/4 HP", wattage: 1587, loadType: "M", label: "6.9A FLC @ 230V" },
      { description: "Standard Motor - 1 HP", wattage: 1840, loadType: "M", label: "8.0A FLC @ 230V" },
      { description: "Standard Motor - 1.5 HP", wattage: 2300, loadType: "M", label: "10.0A FLC @ 230V" },
      { description: "Standard Motor - 2 HP", wattage: 2760, loadType: "M", label: "12.0A FLC @ 230V" },
      { description: "Large Motor - 3 HP", wattage: 3910, loadType: "M", label: "17.0A FLC @ 230V" },
      { description: "Large Motor - 5 HP", wattage: 6440, loadType: "M", label: "28.0A FLC @ 230V" },
      { description: "Heavy Duty Motor - 7.5 HP", wattage: 9200, loadType: "M", label: "40.0A FLC @ 230V" },
      { description: "Industrial Motor - 10 HP", wattage: 11500, loadType: "M", label: "50.0A FLC @ 230V" },
      { description: "Industrial Motor - 15 HP", wattage: 17250, loadType: "M", label: "Three-Phase induction FLC (42A FLC @ 230V 3Ø)" },
      { description: "Industrial Motor - 20 HP", wattage: 21850, loadType: "M", label: "Three-Phase induction FLC (54A FLC @ 230V 3Ø)" },
      { description: "Heavy Duty Industrial Motor - 25 HP", wattage: 27600, loadType: "M", label: "Three-Phase Induction (68A FLC @ 230V 3Ø)" },
      { description: "Heavy Duty Industrial Motor - 30 HP", wattage: 32200, loadType: "M", label: "Three-Phase Induction (80A FLC @ 230V 3Ø)" },
      { description: "High Capacity Industrial Motor - 40 HP", wattage: 41400, loadType: "M", label: "Three-Phase Induction (104A FLC @ 230V 3Ø)" },
      { description: "High Capacity Industrial Motor - 50 HP", wattage: 50600, loadType: "M", label: "Three-Phase Induction (130A FLC @ 230V 3Ø)" },
      { description: "Tank Air Compressor - 5 HP", wattage: 6440, loadType: "M", label: "Workshop Heavy Duty Compressor System" },
      { description: "Industrial Ventilation Exhaust Fan - 2 HP", wattage: 2760, loadType: "M", label: "Warehouse High Flow Blower Fan" }
    ]
  },
  {
    category: "Miscellaneous Loads",
    items: [
      { description: "Elevator", wattage: 7460, loadType: "M", label: "Elevator (5HP – 100HP)" },
      { description: "Escalator", wattage: 3730, loadType: "M", label: "Escalator (3HP – 50HP)" },
      { description: "Fire Alarm System", wattage: 100, loadType: "S", label: "Fire Alarm System (50W – 500W)" },
      { description: "CCTV Power Supply", wattage: 100, loadType: "S", label: "CCTV Power Supply (50W – 300W)" },
      { description: "Server Rack", wattage: 2000, loadType: "S", label: "Server Rack (500W – 5000W)" },
      { description: "Billboard Signage", wattage: 1000, loadType: "L", label: "Billboard Signage (100W – 3000W)" },
      { description: "Electric Gate Motor", wattage: 373, loadType: "M", label: "Electric Gate Motor (0.25HP – 1HP)" },
      { description: "Solar Inverter", wattage: 5000, loadType: "P", label: "Solar Inverter (500W – 10000W)" },
      { description: "EV Charger", wattage: 7000, loadType: "P", label: "EV Charger (3kW – 22kW)" },
      { description: "In-Duct Steam Humidifier", wattage: 1200, loadType: "S", label: "HVAC Humidifier System (1Ø)" },
      { description: "Warehouse Industrial Dehumidifier", wattage: 3000, loadType: "P", label: "High Capacity Floor-space Dehumidifier (3Ø)" },
      { description: "Automatic Lift Basin Sump Pump", wattage: 1500, loadType: "M", label: "Sub-grade chamber drainage pit" },
      { description: "Access Control Boom Gate", wattage: 300, loadType: "M", label: "Parking Toll/Entrance Barrier Lever (1Ø)" },
      { description: "Surge Protection Monitor Panel", wattage: 50, loadType: "S", label: "Active SPD Tracking Control Rack" },
      { description: "Hydraulic Dock Leveler Cylinder", wattage: 1500, loadType: "M", label: "Industrial Leveling Dock Ramp Cylinder Motor (3Ø)" },
      { description: "Emergency Diesel Generator Block Heater", wattage: 500, loadType: "S", label: "GenSet Heater & Battery Float Support (1Ø)" },
      { description: "Pneumatic Capsule Tube Turbine", wattage: 2200, loadType: "M", label: "HVAC Vacuum Capsule Post Transit Fan (3Ø)" }
    ]
  },
  {
    category: "Spares & Spaces",
    items: [
      { description: "SPARE", wattage: 0, loadType: "SP", label: "Spare Circuit" },
      { description: "SPACE", wattage: 0, loadType: "SPACE", label: "Space Only" }
    ]
  }
];
